"""Policy-Gradient emitter for PGA-MAP-Elites, integrated with QDax infrastructure.

Uses QDax's ReplayBuffer, QDTransition, make_td3_loss_fn, and QModule for
a proper TD3-based PG emitter that collects transitions during scoring.

Usage:
    from src.qd_engine.pg_emitter import PGEmitter, PGEmitterConfig

    pg_emitter = PGEmitter(config=PGEmitterConfig(), policy_network=policy_net,
                           obs_dim=env.obs_dim, action_dim=env.action_dim)
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import partial
from typing import Any, Optional, Tuple

import flax.linen as nn
import jax
import jax.numpy as jnp
import optax
from flax import struct

from qdax.core.containers.mapelites_repertoire import MapElitesRepertoire
from qdax.core.emitters.emitter import Emitter, EmitterState
from qdax.core.neuroevolution.buffers.buffer import QDTransition, ReplayBuffer
from qdax.core.neuroevolution.losses.td3_loss import make_td3_loss_fn
from qdax.core.neuroevolution.networks.networks import QModule
from qdax.custom_types import Descriptor, ExtraScores, Fitness, Genotype, Params, RNGKey


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PGEmitterConfig:
    """Configuration for the PG emitter."""
    env_batch_size: int = 64
    num_critic_training_steps: int = 300
    num_pg_training_steps: int = 100

    # TD3 params
    replay_buffer_size: int = 250_000
    critic_hidden_layer_size: Tuple[int, ...] = (256, 256)
    critic_learning_rate: float = 3e-4
    actor_learning_rate: float = 3e-4
    policy_learning_rate: float = 1e-3
    noise_clip: float = 0.5
    policy_noise: float = 0.2
    discount: float = 0.99
    reward_scaling: float = 1.0
    td3_batch_size: int = 256
    soft_tau_update: float = 0.005
    policy_delay: int = 2


# ---------------------------------------------------------------------------
# Emitter state
# ---------------------------------------------------------------------------

@struct.dataclass
class PGEmitterState(EmitterState):
    """Contains training state for the TD3 critic and policy-gradient emitter."""
    critic_params: Params
    critic_optimizer_state: optax.OptState
    actor_params: Params
    actor_opt_state: optax.OptState
    target_critic_params: Params
    target_actor_params: Params
    replay_buffer: ReplayBuffer
    key: RNGKey


# ---------------------------------------------------------------------------
# PG Emitter
# ---------------------------------------------------------------------------

class PGEmitter(Emitter):
    """Policy-gradient emitter using TD3 critic for PGA-MAP-Elites.

    Collects transitions during scoring, trains a shared TD3 critic, then
    applies critic-gradient ascent to parent policies sampled from the archive.

    Uses use_all_data=True so it benefits from transitions generated by ALL
    offspring (GA + PG), not just its own.
    """

    def __init__(
        self,
        config: PGEmitterConfig,
        policy_network: nn.Module,
        obs_dim: int,
        action_dim: int,
    ):
        self._config = config
        self._policy_network = policy_network
        self._obs_dim = obs_dim
        self._action_dim = action_dim
        self._actor_critic_iterations = max(
            1, config.num_critic_training_steps // config.policy_delay
        )

        # Twin critic network (QModule with 2 critics for TD3)
        critic_network = QModule(
            n_critics=2, hidden_layer_sizes=config.critic_hidden_layer_size
        )
        self._critic_network = critic_network

        # TD3 loss functions
        self._policy_loss_fn, self._critic_loss_fn = make_td3_loss_fn(
            policy_fn=policy_network.apply,
            critic_fn=critic_network.apply,
            reward_scaling=config.reward_scaling,
            discount=config.discount,
            noise_clip=config.noise_clip,
            policy_noise=config.policy_noise,
        )

        # Optimizers
        self._actor_optimizer = optax.adam(learning_rate=config.actor_learning_rate)
        self._critic_optimizer = optax.adam(learning_rate=config.critic_learning_rate)
        self._policies_optimizer = optax.adam(learning_rate=config.policy_learning_rate)

    @property
    def batch_size(self) -> int:
        return self._config.env_batch_size

    @property
    def use_all_data(self) -> bool:
        """Use transitions from ALL emitters (GA + PG) to train the critic."""
        return True

    def init(
        self,
        key: RNGKey,
        repertoire: MapElitesRepertoire,
        genotypes: Genotype,
        fitnesses: Fitness,
        descriptors: Descriptor,
        extra_scores: ExtraScores,
    ) -> PGEmitterState:
        """Initialize emitter state with critic networks and replay buffer."""
        key, subkey = jax.random.split(key)

        # Init twin critic
        fake_obs = jnp.zeros((self._obs_dim,))
        fake_action = jnp.zeros((self._action_dim,))
        critic_params = self._critic_network.init(subkey, obs=fake_obs, actions=fake_action)
        target_critic_params = jax.tree.map(lambda x: x, critic_params)

        # Init actor from first genotype in the population
        actor_params = jax.tree.map(lambda x: x[0], genotypes)
        target_actor_params = jax.tree.map(lambda x: x, actor_params)

        # Init optimizer states
        critic_optimizer_state = self._critic_optimizer.init(critic_params)
        actor_optimizer_state = self._actor_optimizer.init(actor_params)

        # Init replay buffer
        dummy_transition = QDTransition.init_dummy(
            observation_dim=self._obs_dim,
            action_dim=self._action_dim,
            descriptor_dim=descriptors.shape[-1] if descriptors.ndim > 1 else 1,
        )
        replay_buffer = ReplayBuffer.init(
            buffer_size=self._config.replay_buffer_size, transition=dummy_transition
        )

        # Seed replay buffer with initial transitions from scoring
        if "transitions" in extra_scores:
            transitions = extra_scores["transitions"]
            replay_buffer = replay_buffer.insert(transitions)

        return PGEmitterState(
            critic_params=critic_params,
            critic_optimizer_state=critic_optimizer_state,
            actor_params=actor_params,
            actor_opt_state=actor_optimizer_state,
            target_critic_params=target_critic_params,
            target_actor_params=target_actor_params,
            replay_buffer=replay_buffer,
            key=key,
        )

    def emit(
        self,
        repertoire: MapElitesRepertoire,
        emitter_state: PGEmitterState,
        key: RNGKey,
    ) -> Tuple[Genotype, ExtraScores]:
        """Emit offspring via policy-gradient improvement of archive parents."""
        batch_size = self._config.env_batch_size

        # Sample parents from repertoire (one fewer for the greedy actor slot)
        mutation_pg_batch_size = max(1, batch_size - 1)
        filled_mask = (repertoire.fitnesses != -jnp.inf).ravel()
        n_filled = jnp.sum(filled_mask)

        # If archive is empty, return random policies
        def emit_when_filled():
            parent_indices = jax.random.choice(
                key,
                jnp.arange(filled_mask.shape[0]),
                shape=(mutation_pg_batch_size,),
                p=filled_mask / jnp.maximum(n_filled, 1),
            )
            parents = jax.tree.map(lambda x: x[parent_indices], repertoire.genotypes)
            return self._emit_pg(emitter_state, parents)

        def emit_when_empty():
            return jax.tree.map(lambda x: jnp.repeat(x[:1], mutation_pg_batch_size, axis=0), repertoire.genotypes)

        offsprings_pg = jax.lax.cond(n_filled > 0, emit_when_filled, emit_when_empty)

        # Also emit the current greedy actor as one offspring
        offspring_actor = jax.tree.map(lambda x: jnp.expand_dims(x, axis=0), emitter_state.actor_params)

        # Concatenate PG offspring + actor
        genotypes = jax.tree.map(
            lambda x, y: jnp.concatenate([x, y], axis=0),
            offsprings_pg,
            offspring_actor,
        )

        return genotypes, {}

    def _emit_pg(
        self, emitter_state: PGEmitterState, parents: Genotype
    ) -> Genotype:
        """Apply num_pg_training_steps of critic-gradient ascent to each parent."""
        # Create a batch of policy optimizer states
        policy_opt_states = jax.vmap(self._policies_optimizer.init)(parents)

        # Batched policy update (vmapped across parents)
        batched_update = jax.vmap(
            partial(self._update_policy, critic_params=emitter_state.critic_params),
            in_axes=(0, 0, None),
        )

        def scan_update_policies(
            carry: Tuple[Params, optax.OptState, RNGKey],
            _: None,
        ) -> Tuple[Tuple[Params, optax.OptState, RNGKey], Any]:
            policy_params, policy_opt_state, key = carry
            key, subkey = jax.random.split(key)

            # Sample mini-batch from replay buffer
            transitions = emitter_state.replay_buffer.sample(
                subkey, self._config.td3_batch_size
            )

            new_params, new_opt_states = batched_update(
                policy_params, policy_opt_state, transitions
            )
            return (new_params, new_opt_states, key), ()

        (final_params, _, final_key), _ = jax.lax.scan(
            scan_update_policies,
            (parents, policy_opt_states, emitter_state.key),
            length=self._config.num_pg_training_steps,
        )

        return final_params

    def state_update(
        self,
        emitter_state: PGEmitterState,
        repertoire: Optional[MapElitesRepertoire] = None,
        genotypes: Optional[Genotype] = None,
        fitnesses: Optional[Fitness] = None,
        descriptors: Optional[Descriptor] = None,
        extra_scores: Optional[ExtraScores] = None,
    ) -> PGEmitterState:
        """Insert transitions into replay buffer and train critic+actor."""
        if extra_scores is None or "transitions" not in extra_scores:
            return emitter_state

        transitions = extra_scores["transitions"]

        # Insert new transitions
        emitter_state = emitter_state.replace(
            replay_buffer=emitter_state.replay_buffer.insert(transitions)
        )

        # Train critic and actor
        final_state, _ = jax.lax.scan(
            self._scan_actor_critic_training,
            emitter_state,
            length=self._actor_critic_iterations,
        )

        return final_state

    def _update_policy(
        self,
        policy_params: Params,
        policy_opt_state: optax.OptState,
        transitions: QDTransition,
        critic_params: Params,
    ) -> Tuple[optax.OptState, Params]:
        """One step of policy-gradient update using the critic as differentiable target."""
        policy_gradient = jax.grad(self._policy_loss_fn)(
            policy_params, critic_params, transitions
        )
        policy_updates, new_opt_state = self._policies_optimizer.update(
            policy_gradient, policy_opt_state
        )
        new_params = optax.apply_updates(policy_params, policy_updates)
        return new_params, new_opt_state

    def _scan_update_critic(
        self,
        carry: Tuple[Params, Params, optax.OptState, Params, RNGKey],
        transitions: QDTransition,
    ) -> Tuple[Tuple[Params, Params, optax.OptState, Params, RNGKey], Any]:
        """One step of critic update with soft target update."""
        critic_params, target_critic_params, critic_opt_state, target_actor_params, key = carry

        key, subkey = jax.random.split(key)
        critic_gradient = jax.grad(self._critic_loss_fn)(
            critic_params, target_actor_params, target_critic_params, transitions, subkey
        )
        critic_updates, new_crit_opt_state = self._critic_optimizer.update(
            critic_gradient, critic_opt_state
        )
        new_crit_params = optax.apply_updates(critic_params, critic_updates)

        # Soft update of target critic
        new_target_crit_params = jax.tree.map(
            lambda x, y: (1.0 - self._config.soft_tau_update) * x + self._config.soft_tau_update * y,
            target_critic_params, new_crit_params,
        )

        return (new_crit_params, new_target_crit_params, new_crit_opt_state, target_actor_params, key), ()

    def _update_actor(
        self,
        actor_params: Params,
        actor_opt_state: optax.OptState,
        target_actor_params: Params,
        critic_params: Params,
        transitions: QDTransition,
    ) -> Tuple[Params, Params, optax.OptState]:
        """One step of actor (greedy policy) update."""
        policy_gradient = jax.grad(self._policy_loss_fn)(
            actor_params, critic_params, transitions
        )
        actor_updates, new_actor_opt_state = self._actor_optimizer.update(
            policy_gradient, actor_opt_state
        )
        new_actor_params = optax.apply_updates(actor_params, actor_updates)

        # Soft update of target actor
        new_target_actor_params = jax.tree.map(
            lambda x, y: (1.0 - self._config.soft_tau_update) * x + self._config.soft_tau_update * y,
            target_actor_params, new_actor_params,
        )

        return new_actor_params, new_target_actor_params, new_actor_opt_state

    def _scan_actor_critic_training(
        self, carry: PGEmitterState, _: None
    ) -> Tuple[PGEmitterState, Tuple]:
        """Packed critic + actor training step (policy_delay critic steps per 1 actor step)."""
        key, subkey = jax.random.split(carry.key)

        # Sample transitions: policy_delay batches for critic + 1 for actor
        total_batch = self._config.td3_batch_size * (self._config.policy_delay + 1)
        transitions = carry.replay_buffer.sample(subkey, total_batch)
        transitions = jax.tree.map(
            lambda x: jnp.reshape(x, (self._config.policy_delay + 1, self._config.td3_batch_size, *x.shape[1:])),
            transitions,
        )

        critic_data = jax.tree.map(lambda x: x[:-1], transitions)
        actor_data = jax.tree.map(lambda x: x[-1], transitions)

        # Train critic (policy_delay steps)
        (new_crit_params, new_target_crit_params, new_crit_opt_state, target_actor_params, key), _ = jax.lax.scan(
            self._scan_update_critic,
            (carry.critic_params, carry.target_critic_params, carry.critic_optimizer_state,
             carry.target_actor_params, key),
            critic_data,
        )

        # Train actor (1 step)
        new_actor_params, new_target_actor_params, new_actor_opt_state = self._update_actor(
            carry.actor_params, carry.actor_opt_state,
            target_actor_params, new_crit_params, actor_data,
        )

        return carry.replace(
            critic_params=new_crit_params,
            critic_optimizer_state=new_crit_opt_state,
            actor_params=new_actor_params,
            actor_opt_state=new_actor_opt_state,
            target_critic_params=new_target_crit_params,
            target_actor_params=new_target_actor_params,
            key=key,
        ), ()
